### Task一覧
GET {{$dotenv %baseurl}}/api/tasks

### Task詳細
GET {{$dotenv %baseurl}}/api/tasks/1

### Task登録
POST {{$dotenv %baseurl}}/api/tasks
X-CSRF-TOKEN: {{$dotenv %csrftoken}}

{
    "title": "new title",
    "content": "new content",
    "person_in_charge": "new person_in_charge1"
}
